/* ============================================================
   VOCABULARY SERVICE — dữ liệu từ vựng + truy vấn dùng chung (cardById, topicById)
   [en, vi, exEn, exVi, pos]
   Thêm/xóa/sửa từ vựng: chỉ cần sửa trong file này, không đụng logic hay UI.
   Thêm chủ đề mới: thêm 1 object {id, name, icon, color, cards:[...]} vào mảng TOPICS.
   ============================================================ */
const TOPICS = [
  {
    id: "family",
    name: "Gia đình",
    icon: "👨‍👩‍👧‍👦",
    color: "#C24444",
    cards: [
      [
        "mother",
        "mẹ",
        "My mother cooks dinner every night.",
        "Mẹ tôi nấu bữa tối mỗi đêm.",
        "danh từ",
      ],
      [
        "father",
        "bố / cha",
        "My father works in a bank.",
        "Bố tôi làm việc ở ngân hàng.",
        "danh từ",
      ],
      [
        "sibling",
        "anh chị em ruột",
        "I have two siblings.",
        "Tôi có hai anh chị em.",
        "danh từ",
      ],
      [
        "grandparent",
        "ông / bà",
        "My grandparents live in the countryside.",
        "Ông bà tôi sống ở nông thôn.",
        "danh từ",
      ],
      [
        "cousin",
        "anh / chị / em họ",
        "My cousin visits us every summer.",
        "Anh họ tôi đến thăm mỗi mùa hè.",
        "danh từ",
      ],
      [
        "spouse",
        "vợ / chồng",
        "She introduced her spouse at the party.",
        "Cô ấy giới thiệu chồng mình tại bữa tiệc.",
        "danh từ",
      ],
      [
        "nephew",
        "cháu trai",
        "My nephew just turned five.",
        "Cháu trai tôi vừa tròn năm tuổi.",
        "danh từ",
      ],
      [
        "niece",
        "cháu gái",
        "My niece loves drawing.",
        "Cháu gái tôi thích vẽ.",
        "danh từ",
      ],
      [
        "relative",
        "họ hàng",
        "Many relatives came to the wedding.",
        "Nhiều họ hàng đến dự đám cưới.",
        "danh từ",
      ],
      [
        "twin",
        "sinh đôi",
        "They are identical twins.",
        "Họ là cặp sinh đôi giống hệt nhau.",
        "danh từ",
      ],
    ],
  },
  {
    id: "food",
    name: "Đồ ăn",
    icon: "🍜",
    color: "#C68A2E",
    cards: [
      [
        "delicious",
        "ngon",
        "This soup is delicious.",
        "Món súp này rất ngon.",
        "tính từ",
      ],
      [
        "recipe",
        "công thức nấu ăn",
        "She shared her secret recipe.",
        "Cô ấy chia sẻ công thức bí mật.",
        "danh từ",
      ],
      [
        "ingredient",
        "nguyên liệu",
        "Fresh ingredients make better meals.",
        "Nguyên liệu tươi tạo nên món ăn ngon hơn.",
        "danh từ",
      ],
      [
        "leftovers",
        "đồ ăn thừa",
        "We had leftovers for lunch.",
        "Chúng tôi ăn đồ thừa cho bữa trưa.",
        "danh từ",
      ],
      [
        "appetizer",
        "món khai vị",
        "Spring rolls are a great appetizer.",
        "Gỏi cuốn là món khai vị tuyệt vời.",
        "danh từ",
      ],
      [
        "beverage",
        "đồ uống",
        "Would you like a beverage?",
        "Bạn có muốn dùng đồ uống không?",
        "danh từ",
      ],
      ["spicy", "cay", "I love spicy food.", "Tôi thích đồ ăn cay.", "tính từ"],
      [
        "bake",
        "nướng (bánh)",
        "We baked cookies together.",
        "Chúng tôi cùng nướng bánh quy.",
        "động từ",
      ],
      [
        "flavor",
        "hương vị",
        "This dish has a rich flavor.",
        "Món này có hương vị đậm đà.",
        "danh từ",
      ],
      [
        "grocery",
        "thực phẩm / tạp hóa",
        "I need to buy groceries.",
        "Tôi cần mua thực phẩm.",
        "danh từ",
      ],
    ],
  },
  {
    id: "travel",
    name: "Du lịch",
    icon: "✈️",
    color: "#2F8577",
    cards: [
      [
        "journey",
        "hành trình",
        "It was a long journey.",
        "Đó là một hành trình dài.",
        "danh từ",
      ],
      [
        "luggage",
        "hành lý",
        "Please check your luggage.",
        "Vui lòng kiểm tra hành lý của bạn.",
        "danh từ",
      ],
      [
        "destination",
        "điểm đến",
        "Paris is our final destination.",
        "Paris là điểm đến cuối cùng của chúng tôi.",
        "danh từ",
      ],
      [
        "itinerary",
        "lịch trình",
        "Here is our travel itinerary.",
        "Đây là lịch trình du lịch của chúng tôi.",
        "danh từ",
      ],
      [
        "passport",
        "hộ chiếu",
        "Don't forget your passport.",
        "Đừng quên mang hộ chiếu.",
        "danh từ",
      ],
      [
        "accommodation",
        "chỗ ở",
        "We booked accommodation near the beach.",
        "Chúng tôi đặt chỗ ở gần biển.",
        "danh từ",
      ],
      [
        "explore",
        "khám phá",
        "Let's explore the old town.",
        "Hãy cùng khám phá phố cổ.",
        "động từ",
      ],
      [
        "souvenir",
        "quà lưu niệm",
        "I bought a souvenir for my mom.",
        "Tôi mua quà lưu niệm cho mẹ.",
        "danh từ",
      ],
      [
        "delay",
        "trì hoãn / chậm trễ",
        "Our flight had a delay.",
        "Chuyến bay của chúng tôi bị trễ.",
        "danh từ",
      ],
      [
        "sightseeing",
        "tham quan",
        "We went sightseeing all day.",
        "Chúng tôi đi tham quan cả ngày.",
        "danh từ",
      ],
    ],
  },
  {
    id: "work",
    name: "Công việc",
    icon: "💼",
    color: "#4A6FA5",
    cards: [
      [
        "deadline",
        "hạn chót",
        "The deadline is tomorrow.",
        "Hạn chót là ngày mai.",
        "danh từ",
      ],
      [
        "colleague",
        "đồng nghiệp",
        "My colleague helped me finish it.",
        "Đồng nghiệp của tôi đã giúp tôi hoàn thành.",
        "danh từ",
      ],
      [
        "meeting",
        "cuộc họp",
        "We have a meeting at 9am.",
        "Chúng tôi có cuộc họp lúc 9 giờ sáng.",
        "danh từ",
      ],
      [
        "salary",
        "lương",
        "She negotiated a higher salary.",
        "Cô ấy đã đàm phán mức lương cao hơn.",
        "danh từ",
      ],
      [
        "promotion",
        "thăng chức",
        "He got a promotion last month.",
        "Anh ấy được thăng chức tháng trước.",
        "danh từ",
      ],
      [
        "resign",
        "từ chức",
        "She decided to resign.",
        "Cô ấy quyết định từ chức.",
        "động từ",
      ],
      [
        "task",
        "nhiệm vụ",
        "This task requires focus.",
        "Nhiệm vụ này đòi hỏi sự tập trung.",
        "danh từ",
      ],
      [
        "schedule",
        "lịch làm việc",
        "Check your schedule for today.",
        "Kiểm tra lịch làm việc hôm nay của bạn.",
        "danh từ",
      ],
      [
        "teamwork",
        "làm việc nhóm",
        "Teamwork made the project succeed.",
        "Làm việc nhóm giúp dự án thành công.",
        "danh từ",
      ],
      [
        "overtime",
        "làm thêm giờ",
        "He worked overtime last week.",
        "Anh ấy đã làm thêm giờ tuần trước.",
        "danh từ",
      ],
    ],
  },
  {
    id: "emotions",
    name: "Cảm xúc",
    icon: "💛",
    color: "#8B5CF6",
    cards: [
      [
        "excited",
        "hào hứng",
        "I'm excited about the trip.",
        "Tôi rất hào hứng về chuyến đi.",
        "tính từ",
      ],
      [
        "anxious",
        "lo lắng",
        "She felt anxious before the exam.",
        "Cô ấy cảm thấy lo lắng trước kỳ thi.",
        "tính từ",
      ],
      [
        "grateful",
        "biết ơn",
        "I'm grateful for your help.",
        "Tôi biết ơn sự giúp đỡ của bạn.",
        "tính từ",
      ],
      [
        "frustrated",
        "bực bội",
        "He was frustrated with the delay.",
        "Anh ấy bực bội vì sự chậm trễ.",
        "tính từ",
      ],
      [
        "relieved",
        "nhẹ nhõm",
        "We felt relieved after the news.",
        "Chúng tôi cảm thấy nhẹ nhõm sau tin đó.",
        "tính từ",
      ],
      [
        "jealous",
        "ghen tị",
        "Don't be jealous of others.",
        "Đừng ghen tị với người khác.",
        "tính từ",
      ],
      [
        "proud",
        "tự hào",
        "Her parents are very proud.",
        "Bố mẹ cô ấy rất tự hào.",
        "tính từ",
      ],
      [
        "lonely",
        "cô đơn",
        "He felt lonely in the city.",
        "Anh ấy cảm thấy cô đơn ở thành phố.",
        "tính từ",
      ],
      [
        "content",
        "hài lòng",
        "She is content with her life.",
        "Cô ấy hài lòng với cuộc sống của mình.",
        "tính từ",
      ],
      [
        "overwhelmed",
        "choáng ngợp / quá tải",
        "I feel overwhelmed with work.",
        "Tôi cảm thấy quá tải với công việc.",
        "tính từ",
      ],
    ],
  },
  {
    id: "weather",
    name: "Thời tiết",
    icon: "☀️",
    color: "#3AA1C7",
    cards: [
      [
        "humid",
        "ẩm ướt",
        "It's humid today.",
        "Hôm nay trời ẩm ướt.",
        "tính từ",
      ],
      [
        "drizzle",
        "mưa phùn",
        "A light drizzle started falling.",
        "Một cơn mưa phùn nhẹ bắt đầu rơi.",
        "danh từ",
      ],
      [
        "thunderstorm",
        "giông bão",
        "A thunderstorm is coming.",
        "Một cơn giông bão đang đến.",
        "danh từ",
      ],
      [
        "breeze",
        "làn gió nhẹ",
        "A cool breeze blew through the window.",
        "Một làn gió mát thổi qua cửa sổ.",
        "danh từ",
      ],
      [
        "forecast",
        "dự báo thời tiết",
        "The forecast predicts rain.",
        "Dự báo thời tiết cho biết trời sẽ mưa.",
        "danh từ",
      ],
      [
        "freezing",
        "lạnh cóng",
        "It's freezing outside.",
        "Bên ngoài lạnh cóng.",
        "tính từ",
      ],
      [
        "sunshine",
        "ánh nắng",
        "We enjoyed the sunshine.",
        "Chúng tôi tận hưởng ánh nắng.",
        "danh từ",
      ],
      [
        "foggy",
        "nhiều sương mù",
        "The road was foggy this morning.",
        "Con đường sáng nay nhiều sương mù.",
        "tính từ",
      ],
      [
        "humidity",
        "độ ẩm",
        "The humidity is very high.",
        "Độ ẩm rất cao.",
        "danh từ",
      ],
      [
        "drought",
        "hạn hán",
        "The region suffered a drought.",
        "Khu vực này đã chịu một trận hạn hán.",
        "danh từ",
      ],
    ],
  },
  {
    id: "sports",
    name: "Thể thao",
    icon: "⚽",
    color: "#DA7A2B",
    cards: [
      [
        "referee",
        "trọng tài",
        "The referee blew the whistle.",
        "Trọng tài thổi còi.",
        "danh từ",
      ],
      [
        "championship",
        "giải vô địch",
        "They won the championship.",
        "Họ đã giành chức vô địch.",
        "danh từ",
      ],
      [
        "teammate",
        "đồng đội",
        "My teammate scored the goal.",
        "Đồng đội của tôi đã ghi bàn.",
        "danh từ",
      ],
      [
        "stadium",
        "sân vận động",
        "The stadium was full.",
        "Sân vận động đã kín chỗ.",
        "danh từ",
      ],
      [
        "coach",
        "huấn luyện viên",
        "Our coach is very strict.",
        "Huấn luyện viên của chúng tôi rất nghiêm khắc.",
        "danh từ",
      ],
      [
        "opponent",
        "đối thủ",
        "We faced a tough opponent.",
        "Chúng tôi đối mặt với một đối thủ mạnh.",
        "danh từ",
      ],
      [
        "training",
        "luyện tập",
        "Training starts at 6am.",
        "Buổi luyện tập bắt đầu lúc 6 giờ sáng.",
        "danh từ",
      ],
      [
        "victory",
        "chiến thắng",
        "It was a great victory.",
        "Đó là một chiến thắng tuyệt vời.",
        "danh từ",
      ],
      [
        "injury",
        "chấn thương",
        "He suffered an injury last game.",
        "Anh ấy bị chấn thương ở trận trước.",
        "danh từ",
      ],
      [
        "tournament",
        "giải đấu",
        "The tournament lasts two weeks.",
        "Giải đấu kéo dài hai tuần.",
        "danh từ",
      ],
    ],
  },
  {
    id: "tech",
    name: "Công nghệ",
    icon: "💻",
    color: "#5B7553",
    cards: [
      [
        "device",
        "thiết bị",
        "This device is very useful.",
        "Thiết bị này rất hữu ích.",
        "danh từ",
      ],
      [
        "update",
        "cập nhật",
        "Please update your app.",
        "Vui lòng cập nhật ứng dụng của bạn.",
        "động từ",
      ],
      [
        "software",
        "phần mềm",
        "The software crashed again.",
        "Phần mềm bị lỗi lần nữa.",
        "danh từ",
      ],
      [
        "password",
        "mật khẩu",
        "Choose a strong password.",
        "Hãy chọn một mật khẩu mạnh.",
        "danh từ",
      ],
      [
        "wireless",
        "không dây",
        "We use a wireless connection.",
        "Chúng tôi sử dụng kết nối không dây.",
        "tính từ",
      ],
      [
        "backup",
        "sao lưu",
        "Always backup your files.",
        "Luôn sao lưu tệp của bạn.",
        "động từ",
      ],
      [
        "malware",
        "phần mềm độc hại",
        "The file contained malware.",
        "Tệp đó chứa phần mềm độc hại.",
        "danh từ",
      ],
      [
        "bandwidth",
        "băng thông",
        "The bandwidth is limited.",
        "Băng thông bị giới hạn.",
        "danh từ",
      ],
      [
        "upload",
        "tải lên",
        "Upload the document here.",
        "Tải tài liệu lên đây.",
        "động từ",
      ],
      [
        "algorithm",
        "thuật toán",
        "The algorithm sorts the data.",
        "Thuật toán sắp xếp dữ liệu.",
        "danh từ",
      ],
    ],
  },
];

const ALL_CARDS = [];
TOPICS.forEach((t) => {
  t.cardObjs = t.cards.map((c, i) => {
    const obj = {
      id: `${t.id}-${i}`,
      topicId: t.id,
      en: c[0],
      vi: c[1],
      exEn: c[2],
      exVi: c[3],
      pos: c[4],
    };
    ALL_CARDS.push(obj);
    return obj;
  });
});
function cardById(id) {
  return ALL_CARDS.find((c) => c.id === id);
}
function topicById(id) {
  return TOPICS.find((t) => t.id === id);
}
